# This is the configuration file for catnip.
# Here you can configure the stat colors,
# stat names, stat icons and more!
#
# https://github.com/iinsertNameHere/catnip

##############################################
##          FetchInfo stats Config          ##
##############################################
[stats]
username  = {icon = " ", name = "username", color = "(RD)"}
#hostname  = {icon = " ", name = "host", color = "(RD)"}
uptime    = {icon = " ", name = "uptime", color = "(BE)"}
distro    = {icon = " ", name = "distro", color = "(BE)"}
kernel    = {icon = "󰭼 ", name = "kernel", color = "(MA)"}
desktop   = {icon = "󱡜 ", name = "windows manager", color = "(MA)"}
terminal  = {icon = " ", name = "terminal", color = "(GN)"}
shell     = {icon = "󰮯 ", name = "shell", color = "(GN)"}
sep_a = "SEPARATOR"
#cpu     = {icon = " ", name = "cpu", color = "(YW)"}
# disk    = {icon = " ", name = "disk", color = "(GN)"}
memory  = {icon = " ", name = "memory", color = "(YW)"}
sep_2 = "SEPARATOR"
colors    = {icon = "󱛜 ", name = "colors", color = "(BK)", symbol = "󱛜 "}

##############################################
##               Misc Config                ##
##############################################
[misc]
borderstyle = "line"
layout = "Inline" # [Inline, ArtOnTop, StatsOnTop]

[misc.figletLogos]
enable = false
color  = "(BE)"
font   = "slant"
margin = [3, 0, 0,]

[misc.imageMode]
enable = false
path   = "/home/nymus/.config/catnap/arch.png" # Please use only absolute paths

scale  = 23
margin = [0, 0, 1]

[nixOS]

